# Generated by Django 5.1.5 on 2025-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.CharField(default='', max_length=255),
        ),
    ]
