# Generated by Django 5.1.5 on 2025-02-02 08:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True),
        ),
    ]
