# Generated by Django 5.1.5 on 2025-03-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='like_count',
            new_name='favorites_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
