# Generated by Django 5.1.5 on 2025-02-23 12:21

import products.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_is_public_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproduct',
            name='image',
            field=models.ImageField(upload_to=products.models.get_upload_to, validators=[utils.validators.validate_image_size, utils.validators.validate_image_dimensions]),
        ),
    ]
