# Generated by Django 5.1.5 on 2025-02-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_imagesproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationsproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product'),
        ),
    ]
