# Generated by Django 5.1.5 on 2025-03-04 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_commentproduct_dislike_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeAndDisLikeComment',
            new_name='VoteComment',
        ),
    ]
