# Generated by Django 5.1.5 on 2025-03-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_likeanddislikecomment_votecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
