# Generated by Django 5.1.5 on 2025-03-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_votecomment_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentproduct',
            old_name='dislike_count',
            new_name='dislikes_count',
        ),
        migrations.RenameField(
            model_name='commentproduct',
            old_name='like_count',
            new_name='likes_count',
        ),
        migrations.AlterField(
            model_name='votecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='products.commentproduct'),
        ),
        migrations.AlterField(
            model_name='votecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
