# Generated by Django 5.1.5 on 2025-03-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_dislike_count_commentproduct_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.commentproduct'),
        ),
    ]
