# Generated by Django 5.1.5 on 2025-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_commentproduct_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
