# Generated by Django 5.1.5 on 2025-03-05 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_commentproduct_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
