# Generated by Django 5.1.5 on 2025-03-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_commentproduct_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comment_count',
            new_name='comments_count',
        ),
    ]
