# Generated by Django 5.1.5 on 2025-03-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_is_public_commentproduct_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
