# Generated by Django 5.1.5 on 2025-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_categoryproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
