# Generated by Django 5.1.5 on 2025-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
